In [1]:
import tensorflow as tf

In [4]:
print(tf.__version__)

1.8.0


In [5]:
hello = tf.constant("Hello")

In [6]:
world = tf.constant("World")

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [13]:
print(result)

b'HelloWorld'


In [14]:
a = tf.constant(10)
b = tf.constant(20)

In [15]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [16]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [17]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [18]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [19]:
result

30

In [37]:
const = tf.constant(10)

In [45]:
fill_mat = tf.fill((4,4),10)

In [46]:
myzeros = tf.zeros((4,4))

In [47]:
myones = tf.ones((4,4))

In [48]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [49]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [50]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [59]:
sess = tf.InteractiveSession()

/home/subhash/anaconda3/envs/snowflakes/lib/python3.6/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [ ]:
for op in my_ops:
    print(sess.run(op))
    print("\n")

In [62]:
a = tf.constant([[1,2],
                [3,4] ])

In [63]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [69]:
b = tf.constant([ [10] , [100] ])

In [70]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [71]:
result = tf.matmul(a,b)

In [72]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [73]:
result.eval()

array([[210],
       [430]], dtype=int32)

## TF Graphs

In [74]:
n1 = tf.constant(1)

In [75]:
n2 = tf.constant(2)

In [76]:
n3 = n1 + n2

In [77]:
n3

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [84]:
with tf.Session() as sess:
    result = sess.run(n3)

In [85]:
print(result)

3


In [94]:
tf.get_default_graph()

In [95]:
g = tf.Graph()
print(g)

In [96]:
graph_one = tf.get_default_graph()

In [103]:
graph_two = tf.Graph()

In [104]:
print(graph_one)
print(graph_two)

In [106]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


In [107]:
print(graph_two is tf.get_default_graph())

False


## Variables and placeholders

In [108]:
sess = tf.InteractiveSession()

/home/subhash/anaconda3/envs/snowflakes/lib/python3.6/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [110]:
my_tensor = tf.random_uniform((4,4),0,1)
my_tensor

<tf.Tensor 'random_uniform_4:0' shape=(4, 4) dtype=float32>

In [111]:
my_var = tf.Variable(initial_value=my_tensor)

In [114]:
init = tf.global_variables_initializer()

In [115]:
sess.run(init)

In [116]:
sess.run(my_var)

array([[0.9032867 , 0.7433077 , 0.14281893, 0.40300274],
       [0.07187092, 0.89032483, 0.5800599 , 0.5910001 ],
       [0.45042443, 0.47016406, 0.6841345 , 0.3139013 ],
       [0.60191834, 0.38278913, 0.64747167, 0.79917276]], dtype=float32)

In [129]:
ph = tf.placeholder(tf.float32)

In [130]:
b = ph*2

In [135]:
with tf.Session() as sess:
    result = sess.run(b,feed_dict={ph:12302})

In [136]:
print(result)

24604.0
